name = "rss-to-memos-sync"
# 默认为 Production 环境
main = "dist/app.mjs"
minify = true
compatibility_date = "2024-10-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "D1"
database_name = "rss-meta"
database_id = "3b38ae7e-ae00-4383-84c1-a4e88d187ff6"

[vars]
# 超时时间(ms)
TIMEOUT = 60000
# 最大请求体大小(字节)，默认 100MB
MAX_BODY_SIZE = 104857600
# # Memos API 地址
# MEMOS_API_URL = ''
# # Memos Access Token
# MEMOS_ACCESS_TOKEN = ''
# # r2-image-uploader 地址
# R2_UPLOADER_URL = ''


[env.dev]
# Development 环境配置
main = "src/app.ts"
minify = false
compatibility_date = "2024-10-20"
compatibility_flags = ["nodejs_compat"]

[[env.dev.d1_databases]]
binding = "D1"
database_name = "rss-meta"
database_id = "3b38ae7e-ae00-4383-84c1-a4e88d187ff6"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
