name: Test
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
      - name: Setup Node.js@lts environment
        uses: actions/setup-node@v7
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run build
      - name: Run tests
        run: pnpm test
      - name: Run tests with coverage
        run: pnpm run test:coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
